palette = "ayumirage"

format = """
$directory\
$git_branch\
$git_status\
$ruby\
$python\
\n$character"""

add_newline = false

[character]
success_symbol = "[~>](bold success)"
error_symbol = "[~>](bold error)"

[directory]
truncation_length = 1
read_only = " 🔒"
style = "directory"

[git_branch]
symbol = "git"
format = '[$symbol:\([$branch](branch)\)](symbol) '
[git_status]
style = "status"

[python]
format = "[ $virtualenv ]($style) "
style = "python"

[ruby]
symbol = " "

# [nodejs]
# symbol = " "
# format = "[$symbol]($style) "
# style = "node"

# [rust]
# symbol = " "
# format = "[$symbol]($style) "
# style = "rust"

# [golang]
# symbol = " "
# format = "[$symbol]($style) "
# style = "go"

[palettes.tokyonight]
error = "#f7768e"
success = "#9ece6a"
directory = "#2ac3de"
branch = "#f7768e"
symbol = "#7dcfff"
status = "#9d7cd8"
python = "#565f89"
node = "#73daca"
rust = "#ff9e64"
go = "#7aa2f7"

[palettes.gruvbox]
error = "#fb4934"
success = "#b8bb26"
directory = "#73daca"
branch = "#fb4934"
symbol = "#83a598"
status = "#928374"
python = "#fabd2f"
node = "#83a598"
rust = "#fe8019"
go = "#83a598"

[palettes.kanagawa]
error = "#E46876"
success = "#98BB6C"
directory = "#7FB4CA"
branch = "#E46876"
symbol = "#7FB4CA"
status = "#54546D"
python = "#DCA561"
node = "#98BB6C"
rust = "#DCA561"
go = "#7FB4CA"

[palettes.catppuccin_mocha]
error = "#F38BA8"
success = "#A6E3A1"
directory = "#89B4FA"
branch = "#F38BA8"
symbol = "#89B4FA"
status = "#9399B2"
python = "#F9E2AF"
node = "#A6E3A1"
rust = "F9E2AF"
go = "#89B4FA"

[palettes.darkplus]
error = "#ff1212"
success = "#4EC9B0"
directory = "#569CD6"
branch = "#FF6B6B"
symbol = "#4EC9B0"
status = "#C586C0"
python = "#DCDCAA"
go = "#9CDCFE"
node = "#4EC9B0"
rust = "#4EC9B0"

[palettes.ayumirage]
error = "#f28779"
success = "#D5FF80"
directory = "#FAD07B"
branch = "#f28779"
symbol = "#73D0FF"
status = "#DFBFFF"
python = "#DCDCAA"
go = "#9CDCFE"
node = "#4EC9B0"
rust = "#4EC9B0"

[palettes.everforestdark]
error = "#E67E81"
success = "#7EB98C"
directory = "#DBBC7F"
branch = "#E67E81"
symbol = "#7FBBB3"
status = "#D699B6"
python = "#DBBC7F"

[palettes.github_dark]
error = "#F25D5D"       # Red-ish tone for errors (GitHub's dark red)
success = "#62D863"     # Green for success
directory = "#8AB6D6"   # Soft blue for directory (matches GitHub dark background)
branch = "#F25D5D"      # Red for git branch (to match the error color)
symbol = "#8AB6D6"      # Light blue for symbol
status = "#6C6C6C"      # Dark gray for status (GitHub dark status bar)
python = "#FFD700"      # Yellow for Python, mimicking GitHub's yellowish tone
node = "#80B6F4"        # Light blue for nodejs (if you choose to use it)
rust = "#D77B7B"        # Rust color that’s not too overpowering (reddish)
go = "#3E8EDE"          # Go language, matching the blue theme of GitHub dark
