cursor #ebe1d4
cursor_text_color #d0c5b4

foreground            #ebe1d4
background            #17130b
selection_foreground  #3a2f15
selection_background  #d8c4a0
url_color             #e9c16c
color0   #17130b
color1   #e14879
color2   #95d66e
color3   #dbb07b
color4   #ab7f23
color5   #ae9663
color6   #e9c16c
color7   #abb2bf
color8   #5c6370
color9   #e05f8c
color10   #a7e086
color11   #e8c397
color12   #f4d089
color13   #a26e3d
color14   #87783a
color15   #ffffff
